# Generated by Django 3.0.8 on 2020-08-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_display', '0002_auto_20200819_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='wash_basin',
            name='item_image1',
            field=models.ImageField(blank=True, null=True, upload_to="{% static 'images' %}"),
        ),
    ]
