# Generated by Django 3.0.8 on 2020-08-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_display', '0003_wash_basin_item_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wash_basin',
            name='item_image1',
            field=models.ImageField(blank=True, null=True, upload_to='main_menu/static/images'),
        ),
    ]
