# Generated by Django 3.0.8 on 2020-08-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_display', '0006_auto_20200821_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wash_basin',
            name='item_image1',
            field=models.ImageField(blank=True, null=True, upload_to='item_display/static/images'),
        ),
    ]
