# Generated by Django 3.0.8 on 2020-08-21 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_display', '0004_auto_20200820_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='wash_basin',
            name='color',
            field=models.CharField(default='white', max_length=20),
            preserve_default=False,
        ),
    ]
