# Generated by Django 3.0.8 on 2020-09-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_display', '0008_auto_20200821_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wash_basin',
            name='brand',
            field=models.CharField(choices=[('Marc', 'Marc'), ('Jayna', 'Jayna'), ('Local', 'Local'), ('Hindware', 'Hindware')], max_length=40),
        ),
    ]
